### ISSUE TITLE
커스텀 response 객체 생성

### ISSUE THREAD

**Issue by D0ri123** [D0ri123/jwp_cat_picture_search#14]
## 📌 Feature Issue
API 호출 응답을 일관성있게 처리하기 위해서 response body를 단일화합니다.

## 📝 To-do
- [x] Common Response 객체 생성
- [x] List Response 객체 생성
- [x] Single Response 객체 생성
- [x] Response Service 생성
