### ISSUE TITLE
일관된 API 응답 형식을 수정

### ISSUE THREAD

**Issue by D0ri123** [D0ri123/jwp_cat_picture_search#17]
## 📌 Feature Issue
API의 응답 형식을 수정할 것입니다.

## 📝 To-do
- [X] Response 객체 재구성
- [X] 예외 관련 응답 형식 구성 후, 클래스 생성
- [X] 에러 코드 정의
- [X] 이미지 랜덤 조회 컨트롤러에 response 형식 적용
